# Generated by Django 4.2.1 on 2023-05-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, verbose_name="category name")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "category",
            },
        ),
        migrations.CreateModel(
            name="OutCome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="updated time"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="quantity"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("UZS", "UZS"), ("RUB", "RUB"), ("USD", "USD")],
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallefy.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "outcome",
                "verbose_name_plural": "outcome",
            },
        ),
        migrations.CreateModel(
            name="InCome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="updated time"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="quantity"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("UZS", "UZS"), ("RUB", "RUB"), ("USD", "USD")],
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallefy.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "income",
                "verbose_name_plural": "income",
            },
        ),
    ]
